// Generated by CoffeeScript 1.3.3
(function() {
  var Module, Subject, Timetable, main;

  Module = (function() {

    function Module(title) {
      this.title = title;
      this.subjects = [];
    }

    return Module;

  })();

  Subject = (function() {

    function Subject(title) {
      this.title = title;
    }

    return Subject;

  })();

  Timetable = (function() {

    function Timetable() {
      this.timetable = [];
    }

    Timetable.prototype.create_week = function() {
      var i, week;
      week = (function() {
        var _i, _results;
        _results = [];
        for (i = _i = 0; _i <= 7; i = ++_i) {
          _results.push(false);
        }
        return _results;
      })();
      this.timetable.push(week);
      return this.timetable.length;
    };

    return Timetable;

  })();

  main = function() {
    var tt;
    tt = new Timetable();
    tt.create_week();
    return console.log(tt.timetable[0]);
  };

  main();

}).call(this);
